/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_azwave_androidzwave_UsbSerialDriver */

#ifndef _Included_com_azwave_androidzwave_UsbSerialDriver
#define _Included_com_azwave_androidzwave_UsbSerialDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_azwave_androidzwave_UsbSerialDriver
 * Method:    SerialOpen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT int JNICALL Java_com_azwave_androidzwave_UsbSerialDriver_SerialOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_azwave_androidzwave_UsbSerialDriver
 * Method:    SerialClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_azwave_androidzwave_UsbSerialDriver_SerialClose
  (JNIEnv *, jobject);

/*
 * Class:     com_azwave_androidzwave_UsbSerialDriver
 * Method:    SerialWrite
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_azwave_androidzwave_UsbSerialDriver_SerialWrite
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_azwave_androidzwave_UsbSerialDriver
 * Method:    SerialRead
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_azwave_androidzwave_UsbSerialDriver_SerialRead
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
